environment: dev
replicaCount: 1
autoscaling:
  enabled: false
image:
  tag: "initial"
vault:
  enabled: true
  role: "backend-dev"
  addr: "https://vault.dev.example.internal"
  dbSecretPath: "secret/data/dev/db"
tags:
  environment: dev
